ItJustWorksTM/EiffelVis

.github/workflows/frontend_ci.yml
frontend/src/components/Graph.tsx

build and lint CI set up for the frontend Closes #11

Frontend ci

---

frontend/src/components/Card.tsx
frontend/src/components/CustomTooltip.tsx
frontend/src/components/Graph.tsx
frontend/src/css/card.module.css
frontend/src/helpers/dataParser.ts

A basic design for the Minimap and Information Box (Tooltip)
Goals:
Closes #19

Minimap and info

---

backend/Cargo.lock
backend/Cargo.toml
backend/Dockerfile
backend/crates/eiffelvis_core/Cargo.toml
backend/crates/eiffelvis_core/src/app.rs
backend/crates/eiffelvis_core/src/graph_storage/chunked_storage.rs
backend/crates/eiffelvis_core/src/graph_storage/mod.rs
backend/crates/eiffelvis_core/src/lib.rs
backend/crates/eiffelvis_core/src/types.rs
backend/crates/eiffelvis_http/Cargo.toml
backend/crates/eiffelvis_http/src/lib.rs
backend/crates/eiffelvis_stream/Cargo.toml
backend/crates/eiffelvis_stream/src/ampq.rs
backend/crates/eiffelvis_stream/src/gen.rs
backend/crates/eiffelvis_stream/src/lib.rs
backend/src/main.rs

The goal here is to populate every proposed crate we got with * something * with the rough direction we want to go in.
bundles #20 with some slight improvements as well as it fits the bill.
__If you ask: "Why drop this huge PR?", well I consumed a critical amount of caffeine and became very motivated..__
before merge:
closes: #6

Setup all crates according to #6 and make backend "functional"

---

backend/tools/event_sender/src/main.rs

Should help us out testing out our realtime networking :)

backend/event_sender: add sleep and burst options

---

frontend/.eslintrc.js
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/Graph.tsx
frontend/src/components/Loader.tsx
frontend/src/components/TooltipCard.tsx
frontend/src/css/controlPanel.css
frontend/src/css/global.css
frontend/src/css/graph.module.css
frontend/src/css/minimap.css
frontend/src/css/spinner.module.css
frontend/src/helpers/dataParser.ts
frontend/src/helpers/useTweakPane.ts
frontend/src/helpers/useWebSocket.ts
frontend/src/interfaces/ApiData.d.ts
frontend/src/interfaces/types.ts

not change to UI. the PR includes the refactored code for the Graph.tsx. main changes are:
- custom hook for the control widget 
- custom hook for the WebSocket

[frontend] refactored graph tsx

---

frontend/src/components/Graph.tsx
frontend/src/helpers/dataParser.ts

Layout Algorithm integrated with real-time stuff.

Layout for graph 

---

backend/crates/eiffelvis_core/src/domain/types.rs
backend/crates/eiffelvis_core/src/domain/user_queries.rs
backend/crates/eiffelvis_gen/src/base_event.rs
backend/crates/eiffelvis_gen/src/generator.rs
frontend/src/components/Graph.tsx
frontend/src/components/TooltipCard.tsx
frontend/src/helpers/useEiffelNet.ts
frontend/src/interfaces/ApiData.d.ts
frontend/src/interfaces/types.ts

did the maths and not alot of benefit for the extra trouble.
closes #49

*: revert time back to u64 as it's a bit silly

---

backend/tools/event_sender/src/main.rs

We recently got our hands on a nice data set :wink: so this support replaying it through the event_sender tool.
adds a `--replay` option that does that.
input file is expected to have a single json event on each line.
Initial playing around shows that we handle it quite well:
Regular scenario:
Likely starts a huge test suite:
using one of those as root:
(needs #47 to actually get these results)

event_sender: Adhoc support to replay files

---

backend/crates/eiffelvis_core/src/graph_storage/chunked_storage.rs
backend/src/main.rs

Hardly any perf change, but should allow the rest of the system to access things much more surgically

Overhaul graph storage indexing

---

backend/crates/eiffelvis_core/src/domain/app.rs
backend/crates/eiffelvis_core/src/domain/types.rs
backend/crates/eiffelvis_core/src/domain/user_queries.rs
backend/crates/eiffelvis_core/src/graph.rs
backend/crates/eiffelvis_core/src/graph_storage/chunked_storage.rs
backend/crates/eiffelvis_core/src/query.rs
backend/crates/eiffelvis_core/src/tracked_query.rs
frontend/src/components/Graph.tsx
frontend/src/helpers/useEiffelNet.ts
frontend/src/interfaces/ApiData.d.ts

Faithful implementation of #61
Implements ranged iterators and usize indexing over the recent chunked graph rework to make this possible in a "proper" way.
Atm, I don't really make sure the ranges are actually proper so let's hope the client is nice for now :)

backend/core: Implement queryv2 (#61)

---

backend/crates/eiffelvis_core/src/domain/user_queries.rs
frontend/src/components/Graph.tsx
frontend/src/interfaces/ApiData.d.ts

Allows more flexibility for the frontend

backend/core: make each node filter many any

---

frontend/src/components/Graph.tsx
frontend/src/css/timebar.css
frontend/src/helpers/dataParser.ts
frontend/src/interfaces/ApiData.d.ts

- Time bar implementation
- Real-time support
- Styling Embedded
Preview
Trend in 4k
Trend in 10k
Trend in 15k

[Frontend] TimeBar implementation

---

frontend/src/components/Graph.tsx
frontend/src/helpers/dataParser.ts
frontend/src/helpers/useCustomShapes.ts
frontend/src/helpers/useLayout.ts
frontend/src/helpers/useTweakPane.ts

Graph Scaling

---

backend/Cargo.lock
backend/crates/eiffelvis_core/src/domain/user_queries.rs
backend/crates/eiffelvis_http/Cargo.toml
backend/crates/eiffelvis_http/src/handlers.rs
backend/crates/eiffelvis_http/src/lib.rs

Backend fixups

---

backend/crates/eiffelvis_core/src/query.rs

backend/core: use ahash for visitmap hasher

---

backend/Cargo.lock
backend/crates/eiffelvis_http/Cargo.toml
backend/crates/eiffelvis_http/src/handlers.rs
backend/crates/eiffelvis_http/src/lib.rs
backend/src/main.rs

using axum-server for simplicity

backend: Wire in support for TLS over http and improve shutdown

---

DEPLOYMENT.md
frontend/.env
frontend/src/App.svelte

Fix the default backend URL with a more generally useful feature

[frontend] Support @hostname backend URL prefix

---

README.md
backend/README.md
backend/crates/eiffelvis_core/README.md
backend/crates/eiffelvis_gen/README.md
backend/crates/eiffelvis_http/README.md
backend/crates/eiffelvis_stream/README.md

Quick write up that briefly explains stuff, partial solves #76

backend: add readme files

---

frontend/src/App.svelte

fixed layout issue

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.svelte
frontend/src/apidefinition.ts
frontend/src/components/G6Graph.svelte

- Optimized TimeBar using hide/show items instead of re-render
- Corresponding styling
- Rewrite for integration with Svelte
- Preview

[frontend] Add back G6 TimeBar to svelte frontend

---

frontend/src/eiffelvis.ts

frontend/eiffelvis.ts: add code documentation

---

frontend/src/components/G6Graph.svelte

frontend/graph: call .render() to actually reset the graph

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.svelte
frontend/src/apidefinition.ts
frontend/src/components/ColorLegend.svelte
frontend/src/components/EventDetail.svelte
frontend/src/components/FilterWidget.svelte
frontend/src/components/G6Graph.svelte
frontend/src/components/GraphOptions.svelte
frontend/src/components/QueryForm.svelte
frontend/src/eiffelvis.ts
frontend/src/layout.ts
frontend/src/main.ts
frontend/src/uitypes.ts
frontend/tsconfig.json

**work in progress**
goals:
- Split up App.svelte into components
- Untangle query consumption and enable query caching
- Clean up networking a bit

frontend: split up App.svelte into components

---

backend/Cargo.lock
backend/Cargo.toml
backend/crates/eiffelvis_core/Cargo.toml
backend/crates/eiffelvis_gen/Cargo.toml
backend/crates/eiffelvis_http/Cargo.toml
backend/crates/eiffelvis_http/src/handlers.rs
backend/crates/eiffelvis_http/src/lib.rs
backend/crates/eiffelvis_stream/Cargo.toml
backend/crates/eiffelvis_stream/src/ampq.rs
backend/src/main.rs
backend/tools/event_sender/Cargo.toml
backend/tools/event_sender/src/main.rs

backend: bring dependencies up to date

---

frontend/src/App.svelte
frontend/src/components/G6Graph.svelte
frontend/src/components/QueryForm.svelte
frontend/src/eiffelvis.ts

frontend: minor code clean up

---

backend/Cargo.lock

backend: Update Cargo.lock

---

frontend/src/App.svelte
frontend/src/components/settings/Settings.svelte
frontend/src/components/shortcut/Shortcut.svelte
frontend/src/components/shortcut/ShortcutPanel.svelte
frontend/src/components/utils/HeaderWithCloseButton.svelte

- Creation of a component shortcut
- Creation of a component shortcut panel, handling a list of shortcuts
- Styling using tailwind only
Should be merged after #149

Frontend: Shortcut Panel
